/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import CakeImage from 'src/assets/images/home_cake.png';
import ButtonPinkImage from 'src/assets/images/aftlogin_button_pink.png';
import Q4Image from 'src/assets/images/aftlogin______.png';
import ButtonPink1Image from 'src/assets/images/aftlogin_button_pink_1.png';
import Q10Image from 'src/assets/images/aftlogin________.png';
import TitleImage from 'src/assets/images/aftlogin_title.png';
import { styled } from '@mui/material/styles';

const AftLogin1 = styled('div')({
  backgroundColor: `rgba(255, 184, 188, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `889px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Cake = styled('img')({
  height: `350px`,
  width: `350px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `21px`,
  top: `128px`,
});

const ButtonList = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `300px`,
  height: `326px`,
  left: `45px`,
  top: `506px`,
});

const Background = styled('div')({
  backgroundColor: `rgba(255, 233, 234, 1)`,
  borderRadius: `40px`,
  width: `300px`,
  height: `326px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Buttons = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `240px`,
  height: `282.55px`,
  left: `30px`,
  top: `22px`,
});

const Q = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `240px`,
  height: `54.55px`,
  left: `0px`,
  top: `228px`,
});

const Q1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  WebkitTextStroke: `1px rgba(30, 95, 69, 1)`,
  position: `absolute`,
  left: `77px`,
  top: `0px`,
});

const ButtonPink = styled('img')({
  height: `54.55px`,
  width: `240px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `5px`,
});

const Q2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `DNF Bit Bit TTF`,
  fontWeight: `400`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  WebkitTextStroke: `1px rgba(75, 44, 46, 1)`,
  position: `absolute`,
  left: `74px`,
  top: `17px`,
});

const Q3 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `240px`,
  height: `54.55px`,
  left: `0px`,
  top: `151px`,
});

const Q4 = styled('img')({
  height: `54.55px`,
  width: `240px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q5 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  WebkitTextStroke: `1px rgba(30, 95, 69, 1)`,
  position: `absolute`,
  left: `77px`,
  top: `0px`,
});

const Q6 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `DNF Bit Bit TTF`,
  fontWeight: `400`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  WebkitTextStroke: `1px rgba(53, 90, 76, 1)`,
  position: `absolute`,
  left: `23px`,
  top: `17px`,
});

const Q7 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `240px`,
  height: `54.55px`,
  left: `0px`,
  top: `75px`,
});

const Q8 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  WebkitTextStroke: `1px rgba(30, 95, 69, 1)`,
  position: `absolute`,
  left: `77px`,
  top: `0px`,
});

const ButtonPink1 = styled('img')({
  height: `54.55px`,
  width: `240px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `5px`,
});

const Q9 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `DNF Bit Bit TTF`,
  fontWeight: `400`,
  fontSize: `28px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  WebkitTextStroke: `1px rgba(75, 44, 46, 1)`,
  position: `absolute`,
  left: `49px`,
  top: `17px`,
});

const Q10 = styled('img')({
  height: `54.55px`,
  width: `240px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Title = styled('img')({
  height: `55px`,
  width: `327px`,
  position: `absolute`,
  left: `31px`,
  top: `72px`,
});

function AftLogin(props) {
  return (
    <AftLogin1 className={props.className}>
      <Cake src={CakeImage} loading="lazy" alt={'cake'} />
      <ButtonList>
        <Background></Background>
        <Buttons>
          <Q>
            {false && <Q1>{`로그인하기`}</Q1>}
            <ButtonPink
              src={ButtonPinkImage}
              loading="lazy"
              alt={'button_pink'}
            />
            <Q2>{`로그아웃`}</Q2>
          </Q>
          <Q3>
            <Q4 src={Q4Image} loading="lazy" alt={'픽셀버튼'} />
            {false && <Q5>{`로그인하기`}</Q5>}
            <Q6>{`내 파티장으로 이동`}</Q6>
          </Q3>
          <Q7>
            {false && <Q8>{`로그인하기`}</Q8>}
            <ButtonPink1
              src={ButtonPink1Image}
              loading="lazy"
              alt={'button_pink'}
            />
            <Q9>{`초대장 보내기`}</Q9>
          </Q7>
          <Q10 src={Q10Image} loading="lazy" alt={'파티안내수칙'} />
        </Buttons>
      </ButtonList>
      <Title src={TitleImage} loading="lazy" alt={'title'} />
    </AftLogin1>
  );
}

export default AftLogin;
