/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import ShortbuttonImage from 'src/assets/images/partyroom_shortbutton.png';
import Chair1Image from 'src/assets/images/partyroom_chair.png';
import Chair2Image from 'src/assets/images/partyroom_chair_1.png';
import Chair3Image from 'src/assets/images/partyroom_chair_2.png';
import Chair4Image from 'src/assets/images/partyroom_chair_3.png';
import Chair5Image from 'src/assets/images/partyroom_chair_4.png';
import Chair6Image from 'src/assets/images/partyroom_chair_5.png';
import Chair7Image from 'src/assets/images/partyroom_chair_6.png';
import Chair8Image from 'src/assets/images/partyroom_chair_7.png';
import Chair9Image from 'src/assets/images/partyroom_chair_8.png';
import Chair10Image from 'src/assets/images/partyroom_chair_9.png';
import Chair11Image from 'src/assets/images/partyroom_chair_10.png';
import Q2Image from 'src/assets/images/partyroom_____.png';
import TableImage from 'src/assets/images/table.png';
import CakeStackImage from 'src/assets/images/partyroom_cake_stack.png';
import CakeStack1Image from 'src/assets/images/partyroom_cake_stack_1.png';
import CakeTopImage from 'src/assets/images/partyroom_cake_top.png';
import { styled } from '@mui/material/styles';

const Partyroom1 = styled('div')({
  backgroundColor: `rgba(255, 184, 188, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `844px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Group16 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `160px`,
  height: `54px`,
  left: `117px`,
  top: `31px`,
});

const Rectangle10 = styled('div')({
  backgroundColor: `rgba(245, 222, 216, 1)`,
  borderRadius: `40px`,
  width: `160px`,
  height: `54px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const DDay = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `DNF Bit Bit TTF`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `113px`,
  height: `20px`,
  position: `absolute`,
  left: `23px`,
  top: `17px`,
});

const Q = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `87.01px`,
  height: `40.55px`,
  left: `292px`,
  top: `793px`,
});

const Shortbutton = styled('img')({
  height: `40.55px`,
  width: `87.01px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `DNF Bit Bit TTF`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  WebkitTextStroke: `1px rgba(53, 90, 76, 1)`,
  width: `45px`,
  height: `22px`,
  position: `absolute`,
  left: `23px`,
  top: `8px`,
});

const Chair = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `331px`,
  height: `528.17px`,
  left: `32px`,
  top: `160px`,
});

const Chair1 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `140px`,
  top: `0px`,
});

const Chair2 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `94px`,
});

const Chair3 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `281px`,
  top: `474px`,
});

const Chair4 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `281px`,
  top: `94px`,
});

const Chair5 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `189px`,
});

const Chair6 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `284px`,
});

const Chair7 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `379px`,
});

const Chair8 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `474px`,
});

const Chair9 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `281px`,
  top: `189px`,
});

const Chair10 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `281px`,
  top: `284px`,
});

const Chair11 = styled('img')({
  height: `54.17px`,
  width: `50px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `281px`,
  top: `379px`,
});

const Q2 = styled('img')({
  height: `125.9px`,
  width: `120px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `137px`,
  top: `97px`,
});

const Table = styled('img')({
  height: `600px`,
  width: `193.55px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `100px`,
  top: `193px`,
});

const CakeStack = styled('img')({
  height: `42px`,
  width: `70px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `160px`,
  top: `283px`,
});

const CakeStack1 = styled('img')({
  height: `42px`,
  width: `70px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `160px`,
  top: `256px`,
});

const CakeTop = styled('img')({
  height: `70px`,
  width: `70px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `160px`,
  top: `201px`,
});

function Partyroom(props) {
  return (
    <Partyroom1 className={props.className}>
      <Group16>
        <Rectangle10></Rectangle10>
        <DDay>{`D - __DAY`}</DDay>
      </Group16>
      <Q>
        <Shortbutton
          src={ShortbuttonImage}
          loading="lazy"
          alt={'shortbutton'}
        />
        <Q1>{`이전`}</Q1>
      </Q>
      <Chair>
        <Chair1 src={Chair1Image} loading="lazy" alt={'chair'} />
        <Chair2 src={Chair2Image} loading="lazy" alt={'chair'} />
        <Chair3 src={Chair3Image} loading="lazy" alt={'chair'} />
        <Chair4 src={Chair4Image} loading="lazy" alt={'chair'} />
        <Chair5 src={Chair5Image} loading="lazy" alt={'chair'} />
        <Chair6 src={Chair6Image} loading="lazy" alt={'chair'} />
        <Chair7 src={Chair7Image} loading="lazy" alt={'chair'} />
        <Chair8 src={Chair8Image} loading="lazy" alt={'chair'} />
        <Chair9 src={Chair9Image} loading="lazy" alt={'chair'} />
        <Chair10 src={Chair10Image} loading="lazy" alt={'chair'} />
        <Chair11 src={Chair11Image} loading="lazy" alt={'chair'} />
      </Chair>
      <Q2 src={Q2Image} loading="lazy" alt={'고라니'} />
      <Table src={TableImage} loading="lazy" alt={'table'} />
      <CakeStack src={CakeStackImage} loading="lazy" alt={'cake_stack'} />
      <CakeStack1 src={CakeStack1Image} loading="lazy" alt={'cake_stack'} />
      <CakeTop src={CakeTopImage} loading="lazy" alt={'cake-top'} />
    </Partyroom1>
  );
}

export default Partyroom;
