/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Q6Image from 'src/assets/images/rules________.png';
import LetterImage from 'src/assets/images/rules_letter.png';
import { styled } from '@mui/material/styles';

const Rules1 = styled('div')({
  backgroundColor: `rgba(255, 184, 188, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `844px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Q = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `159px`,
  height: `58px`,
  position: `absolute`,
  left: `115px`,
  top: `38px`,
});

const Q1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `159px`,
  height: `58px`,
  position: `absolute`,
  left: `107px`,
  top: `155px`,
});

const Q2 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `159px`,
  height: `58px`,
  position: `absolute`,
  left: `107px`,
  top: `227px`,
});

const Q3 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `159px`,
  height: `58px`,
  position: `absolute`,
  left: `107px`,
  top: `320px`,
});

const Q4 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `159px`,
  height: `58px`,
  position: `absolute`,
  left: `107px`,
  top: `384px`,
});

const Q5 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `159px`,
  height: `58px`,
  position: `absolute`,
  left: `114px`,
  top: `456px`,
});

const Q6 = styled('img')({
  height: `54.55px`,
  width: `240px`,
  position: `absolute`,
  left: `75px`,
  top: `731px`,
});

const Letter = styled('img')({
  height: `532.5px`,
  width: `300px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `45px`,
  top: `130px`,
});

function Rules(props) {
  return (
    <Rules1 className={props.className}>
      <Q>{`파티 안내 수칙`}</Q>
      <Q1>{`네티켓 준수`}</Q1>
      <Q2>{`네티켓 준수`}</Q2>
      <Q3>{`네티켓 준수`}</Q3>
      <Q4>{`네티켓 준수`}</Q4>
      <Q5>{`네티켓 준수`}</Q5>
      <Q6 src={Q6Image} loading="lazy" alt={'파티안내수칙'} />
      <Letter src={LetterImage} loading="lazy" alt={'letter'} />
    </Rules1>
  );
}

export default Rules;
